//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageNames() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.LanguageNames", typeof(LanguageNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Afrikaans.
        /// </summary>
        internal static string af {
            get {
                return ResourceManager.GetString("af", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a العَرَبِية.
        /// </summary>
        internal static string ar {
            get {
                return ResourceManager.GetString("ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a български.
        /// </summary>
        internal static string bg {
            get {
                return ResourceManager.GetString("bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Català.
        /// </summary>
        internal static string ca {
            get {
                return ResourceManager.GetString("ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Čeština.
        /// </summary>
        internal static string cs {
            get {
                return ResourceManager.GetString("cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dansk.
        /// </summary>
        internal static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deutsch.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ελληνικά.
        /// </summary>
        internal static string el {
            get {
                return ResourceManager.GetString("el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eesti keel.
        /// </summary>
        internal static string et {
            get {
                return ResourceManager.GetString("et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a فارسى.
        /// </summary>
        internal static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suomi.
        /// </summary>
        internal static string fi {
            get {
                return ResourceManager.GetString("fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Français.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a עברית.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a हिन्दी.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hrvatski.
        /// </summary>
        internal static string hr {
            get {
                return ResourceManager.GetString("hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Magyar.
        /// </summary>
        internal static string hu {
            get {
                return ResourceManager.GetString("hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Italiano.
        /// </summary>
        internal static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 한국어.
        /// </summary>
        internal static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lietuvių kalba.
        /// </summary>
        internal static string lt {
            get {
                return ResourceManager.GetString("lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latviešu valoda.
        /// </summary>
        internal static string lv {
            get {
                return ResourceManager.GetString("lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bokmål.
        /// </summary>
        internal static string nb {
            get {
                return ResourceManager.GetString("nb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nederlands.
        /// </summary>
        internal static string nl {
            get {
                return ResourceManager.GetString("nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nynorsk.
        /// </summary>
        internal static string nn {
            get {
                return ResourceManager.GetString("nn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Polski.
        /// </summary>
        internal static string pl {
            get {
                return ResourceManager.GetString("pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Português (Brasil).
        /// </summary>
        internal static string pt_BR {
            get {
                return ResourceManager.GetString("pt_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Português (Portugal).
        /// </summary>
        internal static string pt_PT {
            get {
                return ResourceManager.GetString("pt_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limba Română.
        /// </summary>
        internal static string ro {
            get {
                return ResourceManager.GetString("ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Русский язык.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Slovenčina.
        /// </summary>
        internal static string sk {
            get {
                return ResourceManager.GetString("sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Slovenščina.
        /// </summary>
        internal static string sl {
            get {
                return ResourceManager.GetString("sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shqip.
        /// </summary>
        internal static string sq {
            get {
                return ResourceManager.GetString("sq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Српски.
        /// </summary>
        internal static string sr_Cyrl {
            get {
                return ResourceManager.GetString("sr_Cyrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Srpski.
        /// </summary>
        internal static string sr_Latn {
            get {
                return ResourceManager.GetString("sr_Latn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Svenska.
        /// </summary>
        internal static string sv {
            get {
                return ResourceManager.GetString("sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Türkçe.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Українська.
        /// </summary>
        internal static string uk {
            get {
                return ResourceManager.GetString("uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiếng việt.
        /// </summary>
        internal static string vi {
            get {
                return ResourceManager.GetString("vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 台語 台灣話.
        /// </summary>
        internal static string zh_TW {
            get {
                return ResourceManager.GetString("zh_TW", resourceCulture);
            }
        }
    }
}
