//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.MiscResources", typeof(MiscResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All ({0}).
        /// </summary>
        internal static string AllCount {
            get {
                return ResourceManager.GetString("AllCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deskewing....
        /// </summary>
        internal static string AutoDeskewing {
            get {
                return ResourceManager.GetString("AutoDeskewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deskew Progress.
        /// </summary>
        internal static string AutoDeskewProgress {
            get {
                return ResourceManager.GetString("AutoDeskewProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when trying to auto save..
        /// </summary>
        internal static string AutoSaveError {
            get {
                return ResourceManager.GetString("AutoSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatic Updates.
        /// </summary>
        internal static string AutoUpdates {
            get {
                return ResourceManager.GetString("AutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unknown error ocurred during the batch scan..
        /// </summary>
        internal static string BatchError {
            get {
                return ResourceManager.GetString("BatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Batch cancelled..
        /// </summary>
        internal static string BatchStatusCancelled {
            get {
                return ResourceManager.GetString("BatchStatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelling.....
        /// </summary>
        internal static string BatchStatusCancelling {
            get {
                return ResourceManager.GetString("BatchStatusCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Batch completed successfully..
        /// </summary>
        internal static string BatchStatusComplete {
            get {
                return ResourceManager.GetString("BatchStatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Batch scan stopped due to error..
        /// </summary>
        internal static string BatchStatusError {
            get {
                return ResourceManager.GetString("BatchStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanning page {0}....
        /// </summary>
        internal static string BatchStatusPage {
            get {
                return ResourceManager.GetString("BatchStatusPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving batch results....
        /// </summary>
        internal static string BatchStatusSaving {
            get {
                return ResourceManager.GetString("BatchStatusSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanning page {0} (scan {1})....
        /// </summary>
        internal static string BatchStatusScanPage {
            get {
                return ResourceManager.GetString("BatchStatusScanPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for scan {0}....
        /// </summary>
        internal static string BatchStatusWaitingForScan {
            get {
                return ResourceManager.GetString("BatchStatusWaitingForScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose Profile.
        /// </summary>
        internal static string ChooseProfile {
            get {
                return ResourceManager.GetString("ChooseProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to clear {0} item(s)?.
        /// </summary>
        internal static string ConfirmClearItems {
            get {
                return ResourceManager.GetString("ConfirmClearItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete {0} item(s)?.
        /// </summary>
        internal static string ConfirmDeleteItems {
            get {
                return ResourceManager.GetString("ConfirmDeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete {0} profiles?.
        /// </summary>
        internal static string ConfirmDeleteMultipleProfiles {
            get {
                return ResourceManager.GetString("ConfirmDeleteMultipleProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete the profile {0}?.
        /// </summary>
        internal static string ConfirmDeleteSingleProfile {
            get {
                return ResourceManager.GetString("ConfirmDeleteSingleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file {0} already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want undo your changes to {0} image(s)?.
        /// </summary>
        internal static string ConfirmResetImages {
            get {
                return ResourceManager.GetString("ConfirmResetImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copying....
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy Progress.
        /// </summary>
        internal static string CopyProgress {
            get {
                return ResourceManager.GetString("CopyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom ({0}x{1} {2}).
        /// </summary>
        internal static string CustomPageSizeFormat {
            get {
                return ResourceManager.GetString("CustomPageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected scanner is busy..
        /// </summary>
        internal static string DeviceBusy {
            get {
                return ResourceManager.GetString("DeviceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The scanner&apos;s cover is open..
        /// </summary>
        internal static string DeviceCoverOpen {
            get {
                return ResourceManager.GetString("DeviceCoverOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected scanner could not be found..
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected scanner is offline..
        /// </summary>
        internal static string DeviceOffline {
            get {
                return ResourceManager.GetString("DeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The scanner has a paper jam..
        /// </summary>
        internal static string DevicePaperJam {
            get {
                return ResourceManager.GetString("DevicePaperJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The scanner is warming up..
        /// </summary>
        internal static string DeviceWarmingUp {
            get {
                return ResourceManager.GetString("DeviceWarmingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have permission to save files at this location..
        /// </summary>
        internal static string DontHavePermission {
            get {
                return ResourceManager.GetString("DontHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download and Install.
        /// </summary>
        internal static string DownloadAndInstall {
            get {
                return ResourceManager.GetString("DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download Error.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download Needed.
        /// </summary>
        internal static string DownloadNeeded {
            get {
                return ResourceManager.GetString("DownloadNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to send an email..
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email PDF Progress.
        /// </summary>
        internal static string EmailPdfProgress {
            get {
                return ResourceManager.GetString("EmailPdfProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want NAPS2 to automatically check for updates?.
        /// </summary>
        internal static string EnableAutoUpdates {
            get {
                return ResourceManager.GetString("EnableAutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred when trying to save the file..
        /// </summary>
        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimated download size: {0} MB.
        /// </summary>
        internal static string EstimatedDownloadSize {
            get {
                return ResourceManager.GetString("EstimatedDownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have unsaved changes. Are you sure you want to exit and discard those changes?.
        /// </summary>
        internal static string ExitWithUnsavedChanges {
            get {
                return ResourceManager.GetString("ExitWithUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file could not be overwritten because it is currently in use..
        /// </summary>
        internal static string FileInUse {
            get {
                return ResourceManager.GetString("FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more files could not be downloaded..
        /// </summary>
        internal static string FilesCouldNotBeDownloaded {
            get {
                return ResourceManager.GetString("FilesCouldNotBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} / {1} files.
        /// </summary>
        internal static string FilesProgressFormat {
            get {
                return ResourceManager.GetString("FilesProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Files.
        /// </summary>
        internal static string FileTypeAllFiles {
            get {
                return ResourceManager.GetString("FileTypeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitmap Files (*.bmp).
        /// </summary>
        internal static string FileTypeBmp {
            get {
                return ResourceManager.GetString("FileTypeBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enhanced Windows MetaFile (*.emf).
        /// </summary>
        internal static string FileTypeEmf {
            get {
                return ResourceManager.GetString("FileTypeEmf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exchangeable Image File (*.exif).
        /// </summary>
        internal static string FileTypeExif {
            get {
                return ResourceManager.GetString("FileTypeExif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GIF File (*.gif).
        /// </summary>
        internal static string FileTypeGif {
            get {
                return ResourceManager.GetString("FileTypeGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Files.
        /// </summary>
        internal static string FileTypeImageFiles {
            get {
                return ResourceManager.GetString("FileTypeImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JPEG File (*.jpg, *.jpeg).
        /// </summary>
        internal static string FileTypeJpeg {
            get {
                return ResourceManager.GetString("FileTypeJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PDF Document (*.pdf).
        /// </summary>
        internal static string FileTypePdf {
            get {
                return ResourceManager.GetString("FileTypePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PNG File (*.png).
        /// </summary>
        internal static string FileTypePng {
            get {
                return ResourceManager.GetString("FileTypePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIFF File (*.tiff, *.tif).
        /// </summary>
        internal static string FileTypeTiff {
            get {
                return ResourceManager.GetString("FileTypeTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image saved..
        /// </summary>
        internal static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} images saved..
        /// </summary>
        internal static string ImagesSaved {
            get {
                return ResourceManager.GetString("ImagesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file &apos;{0}&apos; could not be imported..
        /// </summary>
        internal static string ImportErrorCouldNot {
            get {
                return ResourceManager.GetString("ImportErrorCouldNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file &apos;{0}&apos; could not be imported. Only PDF files generated by NAPS2 can be imported..
        /// </summary>
        internal static string ImportErrorNAPS2Pdf {
            get {
                return ResourceManager.GetString("ImportErrorNAPS2Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importing....
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importing {0}....
        /// </summary>
        internal static string ImportingFormat {
            get {
                return ResourceManager.GetString("ImportingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import Progress.
        /// </summary>
        internal static string ImportProgress {
            get {
                return ResourceManager.GetString("ImportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installation Complete.
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installation complete. Do you want to restart NAPS2 now?.
        /// </summary>
        internal static string InstallCompletePromptRestart {
            get {
                return ResourceManager.GetString("InstallCompletePromptRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installation failed..
        /// </summary>
        internal static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Installation Failed.
        /// </summary>
        internal static string InstallFailedTitle {
            get {
                return ResourceManager.GetString("InstallFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ({1}x{2} {3}).
        /// </summary>
        internal static string NamedPageSizeFormat {
            get {
                return ResourceManager.GetString("NamedPageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name missing..
        /// </summary>
        internal static string NameMissing {
            get {
                return ResourceManager.GetString("NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NAPS2.
        /// </summary>
        internal static string NAPS2 {
            get {
                return ResourceManager.GetString("NAPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No device selected..
        /// </summary>
        internal static string NoDeviceSelected {
            get {
                return ResourceManager.GetString("NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No scanning device was found..
        /// </summary>
        internal static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected scanner does not support using duplex. If your scanner is supposed to support duplex, try using a different driver..
        /// </summary>
        internal static string NoDuplexSupport {
            get {
                return ResourceManager.GetString("NoDuplexSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected scanner does not support using a feeder. If your scanner does have a feeder, try using a different driver..
        /// </summary>
        internal static string NoFeederSupport {
            get {
                return ResourceManager.GetString("NoFeederSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No pages are in the feeder..
        /// </summary>
        internal static string NoPagesInFeeder {
            get {
                return ResourceManager.GetString("NoPagesInFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Now.
        /// </summary>
        internal static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An update to OCR is available..
        /// </summary>
        internal static string OcrUpdateAvailable {
            get {
                return ResourceManager.GetString("OcrUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of {0}.
        /// </summary>
        internal static string OfN {
            get {
                return ResourceManager.GetString("OfN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overwrite File.
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An additional component is needed to import this PDF file. Would you like to download it now?.
        /// </summary>
        internal static string PdfImportComponentNeeded {
            get {
                return ResourceManager.GetString("PdfImportComponentNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have permission to copy content from the file &apos;{0}&apos;..
        /// </summary>
        internal static string PdfNoPermissionToExtractContent {
            get {
                return ResourceManager.GetString("PdfNoPermissionToExtractContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PDF saved..
        /// </summary>
        internal static string PdfSaved {
            get {
                return ResourceManager.GetString("PdfSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} of {1}.
        /// </summary>
        internal static string PdfStatus {
            get {
                return ResourceManager.GetString("PdfStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} / {1}.
        /// </summary>
        internal static string ProgressFormat {
            get {
                return ResourceManager.GetString("ProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recovering....
        /// </summary>
        internal static string Recovering {
            get {
                return ResourceManager.GetString("Recovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recovery Progress.
        /// </summary>
        internal static string RecoveryProgress {
            get {
                return ResourceManager.GetString("RecoveryProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset Image.
        /// </summary>
        internal static string ResetImage {
            get {
                return ResourceManager.GetString("ResetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Images Progress.
        /// </summary>
        internal static string SaveImagesProgress {
            get {
                return ResourceManager.GetString("SaveImagesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save PDF Progress.
        /// </summary>
        internal static string SavePdfProgress {
            get {
                return ResourceManager.GetString("SavePdfProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving {0}....
        /// </summary>
        internal static string SavingFormat {
            get {
                return ResourceManager.GetString("SavingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanned Image.
        /// </summary>
        internal static string ScannedImage {
            get {
                return ResourceManager.GetString("ScannedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scanning page {0}.
        /// </summary>
        internal static string ScanPageProgress {
            get {
                return ResourceManager.GetString("ScanPageProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected ({0}).
        /// </summary>
        internal static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a profile before clicking Scan..
        /// </summary>
        internal static string SelectProfileBeforeScan {
            get {
                return ResourceManager.GetString("SelectProfileBeforeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} / {1} MB.
        /// </summary>
        internal static string SizeProgress {
            get {
                return ResourceManager.GetString("SizeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred with the scanning driver..
        /// </summary>
        internal static string UnknownDriverError {
            get {
                return ResourceManager.GetString("UnknownDriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsaved Changes.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A newer version of NAPS2 is available. Do you want to update now?.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
