//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Black &amp; White.
        /// </summary>
        internal static string BitDepth_1BlackAndWhite {
            get {
                return ResourceManager.GetString("BitDepth_1BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 24-bit Color.
        /// </summary>
        internal static string BitDepth_24Color {
            get {
                return ResourceManager.GetString("BitDepth_24Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grayscale.
        /// </summary>
        internal static string BitDepth_8Grayscale {
            get {
                return ResourceManager.GetString("BitDepth_8Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 100 dpi.
        /// </summary>
        internal static string Dpi_100 {
            get {
                return ResourceManager.GetString("Dpi_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1200 dpi.
        /// </summary>
        internal static string Dpi_1200 {
            get {
                return ResourceManager.GetString("Dpi_1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 150 dpi.
        /// </summary>
        internal static string Dpi_150 {
            get {
                return ResourceManager.GetString("Dpi_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200 dpi.
        /// </summary>
        internal static string Dpi_200 {
            get {
                return ResourceManager.GetString("Dpi_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 300 dpi.
        /// </summary>
        internal static string Dpi_300 {
            get {
                return ResourceManager.GetString("Dpi_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 400 dpi.
        /// </summary>
        internal static string Dpi_400 {
            get {
                return ResourceManager.GetString("Dpi_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 600 dpi.
        /// </summary>
        internal static string Dpi_600 {
            get {
                return ResourceManager.GetString("Dpi_600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 800 dpi.
        /// </summary>
        internal static string Dpi_800 {
            get {
                return ResourceManager.GetString("Dpi_800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center.
        /// </summary>
        internal static string HorizontalAlign_Center {
            get {
                return ResourceManager.GetString("HorizontalAlign_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left.
        /// </summary>
        internal static string HorizontalAlign_Left {
            get {
                return ResourceManager.GetString("HorizontalAlign_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right.
        /// </summary>
        internal static string HorizontalAlign_Right {
            get {
                return ResourceManager.GetString("HorizontalAlign_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A3 (297x420 mm).
        /// </summary>
        internal static string PageSize_A3 {
            get {
                return ResourceManager.GetString("PageSize_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A4 (210x297 mm).
        /// </summary>
        internal static string PageSize_A4 {
            get {
                return ResourceManager.GetString("PageSize_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A5 (148x210 mm).
        /// </summary>
        internal static string PageSize_A5 {
            get {
                return ResourceManager.GetString("PageSize_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B4 (250x353 mm).
        /// </summary>
        internal static string PageSize_B4 {
            get {
                return ResourceManager.GetString("PageSize_B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B5 (176x250 mm).
        /// </summary>
        internal static string PageSize_B5 {
            get {
                return ResourceManager.GetString("PageSize_B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom....
        /// </summary>
        internal static string PageSize_Custom {
            get {
                return ResourceManager.GetString("PageSize_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a US Legal (8.5x14 in).
        /// </summary>
        internal static string PageSize_Legal {
            get {
                return ResourceManager.GetString("PageSize_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a US Letter (8.5x11 in).
        /// </summary>
        internal static string PageSize_Letter {
            get {
                return ResourceManager.GetString("PageSize_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cm.
        /// </summary>
        internal static string PageSizeUnit_Centimetre {
            get {
                return ResourceManager.GetString("PageSizeUnit_Centimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in.
        /// </summary>
        internal static string PageSizeUnit_Inch {
            get {
                return ResourceManager.GetString("PageSizeUnit_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mm.
        /// </summary>
        internal static string PageSizeUnit_Millimetre {
            get {
                return ResourceManager.GetString("PageSizeUnit_Millimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1:1.
        /// </summary>
        internal static string Scale_1_1 {
            get {
                return ResourceManager.GetString("Scale_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1:2.
        /// </summary>
        internal static string Scale_1_2 {
            get {
                return ResourceManager.GetString("Scale_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1:4.
        /// </summary>
        internal static string Scale_1_4 {
            get {
                return ResourceManager.GetString("Scale_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1:8.
        /// </summary>
        internal static string Scale_1_8 {
            get {
                return ResourceManager.GetString("Scale_1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duplex.
        /// </summary>
        internal static string Source_Duplex {
            get {
                return ResourceManager.GetString("Source_Duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feeder.
        /// </summary>
        internal static string Source_Feeder {
            get {
                return ResourceManager.GetString("Source_Feeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Glass.
        /// </summary>
        internal static string Source_Glass {
            get {
                return ResourceManager.GetString("Source_Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        internal static string TwainImpl_Default {
            get {
                return ResourceManager.GetString("TwainImpl_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legacy (native UI only).
        /// </summary>
        internal static string TwainImpl_Legacy {
            get {
                return ResourceManager.GetString("TwainImpl_Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alternative Transfer.
        /// </summary>
        internal static string TwainImpl_MemXfer {
            get {
                return ResourceManager.GetString("TwainImpl_MemXfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Old DSM.
        /// </summary>
        internal static string TwainImpl_OldDsm {
            get {
                return ResourceManager.GetString("TwainImpl_OldDsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a x64.
        /// </summary>
        internal static string TwainImpl_X64 {
            get {
                return ResourceManager.GetString("TwainImpl_X64", resourceCulture);
            }
        }
    }
}
